// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from 'node:path';
import { defineConfig } from 'prisma/config';
import { config as loadEnv } from 'dotenv';

loadEnv({ path: path.join(process.cwd(), '.env'), quiet: true });
loadEnv({ path: path.join(process.cwd(), '..', '.env'), quiet: true });

const provider = normalizeDatabaseProvider(process.env.DATABASE_PROVIDER);
const url = selectDatabaseUrl(provider);

if (!url) {
    throw new Error(
        `No valid ${provider} database URL configured. Set DATABASE_URL or the provider-specific URL.`,
    );
}

function normalizeDatabaseProvider(value?: string) {
    const provider = (value?.trim() || 'postgresql').toLowerCase();

    if (provider === 'postgres' || provider === 'postgresql') {
        return 'postgresql';
    }

    if (provider === 'mysql') {
        return 'mysql';
    }

    throw new Error(
        `Unsupported DATABASE_PROVIDER "${value}". Use "postgresql" or "mysql".`,
    );
}

function selectDatabaseUrl(databaseProvider: string) {
    const candidates =
        databaseProvider === 'mysql'
            ? [process.env.MYSQL_DATABASE_URL, process.env.DATABASE_URL]
            : [
                  process.env.POSTGRES_DATABASE_URL,
                  process.env.DATABASE_URL,
                  process.env.TEMPLATE_DB_URL,
              ];

    return candidates.find((candidate) =>
        candidate ? urlMatchesProvider(candidate, databaseProvider) : false,
    );
}

function urlMatchesProvider(url: string, databaseProvider: string) {
    return databaseProvider === 'mysql'
        ? url.startsWith('mysql://')
        : url.startsWith('postgresql://') || url.startsWith('postgres://');
}

export default defineConfig({
    schema: 'prisma/schema',
    migrations: {
        path: 'prisma/migrations',
        seed: 'tsx prisma/seed.ts',
    },
    datasource: {
        url,
    },
});
