export interface PermissionCatalogItem {
    key: string;
    labelEn: string;
    labelAr: string;
    description: string;
    category: string;
}

const permissionKeys = [
    'dashboard.page.view',
    'inventory.page.view',
    'alerts.page.view',
    'replenishment.page.view',
    'salesPerformance.page.view',
    'stockCoverage.page.view',
    'stockRules.page.view',
    'logistics.page.view',
    'multiLocation.page.view',
    'snapshots.page.view',
    'users.page.view',
    'roles.page.view',
    'settings.page.view',
    'dashboard.tabs.stockCoverage.view',
    'dashboard.tabs.stockHealth.view',
    'dashboard.tabs.autoAlerts.view',
    'dashboard.tabs.reorderSuggestions.view',
    'dashboard.tabs.inventoryMovement.view',
    'dashboard.tabs.salesPerformance.view',
    'inventory.tabs.movement.view',
    'inventory.tabs.slowStock.view',
    'inventory.tabs.fastStock.view',
    'inventory.tabs.mediumStock.view',
    'inventory.tabs.snapshots.view',
    'inventory.tabs.warehouseBreakdown.view',
    'inventory.tabs.modelBreakdown.view',
    'inventory.tabs.colorBreakdown.view',
    'salesPerformance.tabs.overview.view',
    'salesPerformance.tabs.salesByModel.view',
    'salesPerformance.tabs.salesByColor.view',
    'salesPerformance.tabs.sellerKPIs.view',
    'salesPerformance.tabs.branchPerformance.view',
    'dashboard.cards.totalInventory.view',
    'dashboard.cards.slowStock.view',
    'dashboard.cards.mediumStock.view',
    'dashboard.cards.fastStock.view',
    'dashboard.cards.stockCoverageMonths.view',
    'dashboard.cards.stockHealth.view',
    'dashboard.cards.autoAlerts.view',
    'dashboard.cards.reorderSuggestions.view',
    'dashboard.cards.inventoryTurnover.view',
    'dashboard.cards.daysInStock.view',
    'dashboard.cards.totalSales.view',
    'dashboard.cards.availableVehicles.view',
    'dashboard.cards.reservedVehicles.view',
    'dashboard.cards.soldVehicles.view',
    'inventory.cards.totalVehicles.view',
    'inventory.cards.slowVehicles.view',
    'inventory.cards.mediumVehicles.view',
    'inventory.cards.fastVehicles.view',
    'inventory.cards.byModel.view',
    'inventory.cards.byWarehouse.view',
    'inventory.cards.byColor.view',
    'inventory.cards.byBrand.view',
    'inventory.tables.slowStockList.view',
    'inventory.tables.vehicleMovement.view',
    'inventory.tables.stockByModel.view',
    'inventory.tables.stockByModelColor.view',
    'inventory.tables.stockByWarehouse.view',
    'inventory.tables.stockByVin.view',
    'inventory.tables.stockAgeClassification.view',
    'replenishment.tables.reorderReport.view',
    'replenishment.tables.minMaxRules.view',
    'replenishment.tables.suggestedOrders.view',
    'salesPerformance.tables.salesByModel.view',
    'salesPerformance.tables.salesByColor.view',
    'salesPerformance.tables.sellerKPIs.view',
    'salesPerformance.tables.salesByBranch.view',
    'alerts.tables.alertsWithVin.view',
    'alerts.tables.slowStockAlerts.view',
    'alerts.tables.lowQuantityAlerts.view',
    'alerts.tables.reorderPointAlerts.view',
    'snapshots.tables.snapshotHistory.view',
    'dashboard.charts.inventoryOverview.view',
    'dashboard.charts.stockHealth.view',
    'dashboard.charts.stockCoverage.view',
    'inventory.charts.ageClassification.view',
    'inventory.charts.modelDistribution.view',
    'inventory.charts.colorDistribution.view',
    'salesPerformance.charts.salesTrend.view',
    'salesPerformance.charts.sellerPerformance.view',
    'replenishment.charts.reorderSuggestions.view',
    'data.vin.view',
    'data.chassis.view',
    'data.model.view',
    'data.trim.view',
    'data.color.view',
    'data.brand.view',
    'data.warehouse.view',
    'data.branch.view',
    'data.cost.view',
    'data.salesValue.view',
    'data.profit.view',
    'data.customerInfo.view',
    'data.customerPhone.view',
    'data.sellerName.view',
    'data.supplierInfo.view',
    'data.purchaseDate.view',
    'data.daysInStock.view',
    'data.inventoryKey.view',
    'data.businessStateKey.view',
    'data.sourceRowIndex.view',
    'data.rowHash.view',
    'data.syncRunId.view',
    'data.absEntry.view',
    'data.itemCode.view',
    'data.itemGroupCode.view',
    'data.type.view',
    'data.modelYear.view',
    'data.exteriorColor.view',
    'data.interiorColor.view',
    'data.wheel.view',
    'data.notes.view',
    'data.quantity.view',
    'data.ready.view',
    'data.engineNo.view',
    'data.price1.view',
    'data.listNum1.view',
    'data.listName1.view',
    'data.price2.view',
    'data.listNum2.view',
    'data.listName2.view',
    'data.price3.view',
    'data.listNum3.view',
    'data.price4.view',
    'data.listNum4.view',
    'data.poNo.view',
    'data.estimatedArrival.view',
    'data.grpoDate.view',
    'data.salesMan.view',
    'data.arInvoiceDate.view',
    'data.soldPrice.view',
    'data.vat.view',
    'data.customerName.view',
    'data.customerGroup.view',
    'data.plateNumber.view',
    'data.apInvoiceDate.view',
    'data.apInvoiceNo.view',
    'data.chassisStatus.view',
    'data.displayStatus.view',
    'data.normalizedStatus.view',
    'data.arInvoiceNo.view',
    'data.cardCode.view',
    'data.createDate.view',
    'data.bank.view',
    'data.bankCode.view',
    'data.contractDate.view',
    'data.reserveDate.view',
    'data.customerNumber.view',
    'data.recipientName.view',
    'data.recipientNumber.view',
    'data.uTanazol.view',
    'data.uMobNum.view',
    'data.soRemarks.view',
    'data.additionalRemark.view',
    'data.sourceId.view',
    'data.sourceName.view',
    'data.sourceCountry.view',
    'data.sourceBaseUrl.view',
    'data.stockAgeDays.view',
    'data.movementCategory.view',
    'data.isSold.view',
    'data.isReserved.view',
    'data.isInStock.view',
    'data.isReadyForSale.view',
    'data.rawStatus.view',
    'countries.jordan.view',
    'countries.saudiArabia.view',
    'companies.baraka.view',
    'companies.dania.view',
    'companies.laith.view',
    'companies.laithCars.view',
    'actions.export.view',
    'actions.export.execute',
    'actions.import.execute',
    'actions.syncInventory.execute',
    'actions.editStockRules.execute',
    'actions.createSnapshot.execute',
    'actions.deleteSnapshot.execute',
    'actions.refreshDashboard.execute',
    'actions.sendAlert.execute',
    'actions.updateReorderRules.execute',
    'users.view',
    'users.manage',
    'users.create',
    'users.edit',
    'users.delete',
    'users.activate',
    'users.assignRoles',
    'users.editPermissions',
    'roles.view',
    'roles.manage',
    'roles.create',
    'roles.edit',
    'roles.delete',
    'roles.editPermissions',
    'permissions.view',
    'permissions.manage',
    'settings.view',
    'settings.manage',
    'dashboard.view',
    'inventory.view',
    'inventory.sync',
    'inventory.export',
    'alerts.view',
    'replenishment.view',
    'stockCoverage.view',
    'salesPerformance.view',
    'logistics.view',
    'multiLocation.view',
    'stockRules.view',
    'stockRules.manage',
    'snapshots.view',
] as const;

const englishLabels: Record<string, string> = {
    absEntry: 'ABS entry',
    actions: 'Actions',
    activate: 'Activate',
    additionalRemark: 'Additional remark',
    alerts: 'Alerts',
    alertsWithVin: 'Alerts with VIN',
    apInvoiceDate: 'AP invoice date',
    apInvoiceNo: 'AP invoice number',
    arInvoiceDate: 'AR invoice date',
    arInvoiceNo: 'AR invoice number',
    assignRoles: 'Assign roles',
    autoAlerts: 'Auto alerts',
    availableVehicles: 'Available vehicles',
    bank: 'Bank',
    bankCode: 'Bank code',
    baraka: 'Al Baraka',
    branch: 'Branch',
    branchPerformance: 'Branch performance',
    brand: 'Brand',
    byBrand: 'By brand',
    byColor: 'By color',
    byModel: 'By model',
    byWarehouse: 'By warehouse',
    cards: 'Cards',
    charts: 'Charts',
    chassis: 'Chassis',
    chassisStatus: 'Chassis status',
    color: 'Color',
    colorDistribution: 'Color distribution',
    companies: 'Companies',
    contractDate: 'Contract date',
    cost: 'Cost',
    countries: 'Countries',
    create: 'Create',
    createSnapshot: 'Create snapshot',
    createDate: 'Create date',
    customerGroup: 'Customer group',
    customerInfo: 'Customer information',
    customerName: 'Customer name',
    customerNumber: 'Customer number',
    customerPhone: 'Customer phone',
    dashboard: 'Dashboard',
    dania: 'Dania',
    data: 'Data fields',
    daysInStock: 'Days in stock',
    delete: 'Delete',
    deleteSnapshot: 'Delete snapshot',
    displayStatus: 'Display status',
    edit: 'Edit',
    editPermissions: 'Edit permissions',
    editStockRules: 'Edit stock rules',
    engineNo: 'Engine number',
    estimatedArrival: 'Estimated arrival',
    execute: 'Execute',
    export: 'Export',
    exteriorColor: 'Exterior color',
    fastStock: 'Fast stock',
    fastVehicles: 'Fast vehicles',
    grpoDate: 'GRPO date',
    import: 'Import',
    interiorColor: 'Interior color',
    inventory: 'Inventory',
    inventoryMovement: 'Inventory movement',
    inventoryOverview: 'Inventory overview',
    inventoryTurnover: 'Inventory turnover',
    inventoryKey: 'Inventory key',
    isInStock: 'In stock flag',
    isReadyForSale: 'Ready for sale flag',
    isReserved: 'Reserved flag',
    isSold: 'Sold flag',
    itemCode: 'Item code',
    itemGroupCode: 'Item group code',
    jordan: 'Jordan',
    laith: 'Al Laith Al Lame',
    laithCars: 'Al Laith Cars',
    listName1: 'Price list 1 name',
    listName2: 'Price list 2 name',
    listNum1: 'Price list 1 number',
    listNum2: 'Price list 2 number',
    listNum3: 'Price list 3 number',
    listNum4: 'Price list 4 number',
    logistics: 'Logistics',
    lowQuantityAlerts: 'Low quantity alerts',
    manage: 'Manage',
    mediumStock: 'Medium stock',
    mediumVehicles: 'Medium vehicles',
    minMaxRules: 'Min/max rules',
    model: 'Model',
    modelBreakdown: 'Model breakdown',
    modelDistribution: 'Model distribution',
    modelYear: 'Model year',
    movement: 'Movement',
    movementCategory: 'Movement category',
    multiLocation: 'Multi-location',
    normalizedStatus: 'Normalized status',
    notes: 'Notes',
    overview: 'Overview',
    page: 'Page',
    permissions: 'Permissions',
    plateNumber: 'Plate number',
    poNo: 'PO number',
    price1: 'Price 1',
    price2: 'Price 2',
    price3: 'Price 3',
    price4: 'Price 4',
    profit: 'Profit',
    purchaseDate: 'Purchase date',
    quantity: 'Quantity',
    rawStatus: 'Raw status',
    ready: 'Ready',
    recipientName: 'Recipient name',
    recipientNumber: 'Recipient number',
    refreshDashboard: 'Refresh dashboard',
    reorderPointAlerts: 'Reorder point alerts',
    reorderReport: 'Reorder report',
    reorderSuggestions: 'Reorder suggestions',
    replenishment: 'Replenishment',
    reserveDate: 'Reserve date',
    reservedVehicles: 'Reserved vehicles',
    rowHash: 'Row hash',
    roles: 'Roles',
    salesMan: 'Salesman',
    salesByBranch: 'Sales by branch',
    salesByColor: 'Sales by color',
    salesByModel: 'Sales by model',
    salesPerformance: 'Sales performance',
    salesTrend: 'Sales trend',
    salesValue: 'Sales value',
    saudiArabia: 'Saudi Arabia',
    sellerKPIs: 'Seller KPIs',
    sellerName: 'Seller name',
    sellerPerformance: 'Seller performance',
    sendAlert: 'Send alert',
    settings: 'Settings',
    slowStock: 'Slow stock',
    slowStockAlerts: 'Slow stock alerts',
    slowStockList: 'Slow stock list',
    slowVehicles: 'Slow vehicles',
    snapshots: 'Snapshots',
    snapshotHistory: 'Snapshot history',
    soldVehicles: 'Sold vehicles',
    soldPrice: 'Sold price',
    soRemarks: 'SO remarks',
    sourceBaseUrl: 'Source base URL',
    sourceCountry: 'Source country',
    sourceId: 'Source ID',
    sourceName: 'Source name',
    sourceRowIndex: 'Source row index',
    stockAgeClassification: 'Stock age classification',
    stockAgeDays: 'Stock age days',
    stockByModel: 'Stock by model',
    stockByModelColor: 'Stock by model and color',
    stockByVin: 'Stock by VIN',
    stockByWarehouse: 'Stock by warehouse',
    stockCoverage: 'Stock coverage',
    stockCoverageMonths: 'Stock coverage months',
    stockHealth: 'Stock health',
    stockRules: 'Stock rules',
    suggestedOrders: 'Suggested orders',
    supplierInfo: 'Supplier information',
    sync: 'Sync',
    syncInventory: 'Sync inventory',
    syncRunId: 'Sync run ID',
    tables: 'Tables',
    tabs: 'Tabs',
    totalInventory: 'Total inventory',
    totalSales: 'Total sales',
    totalVehicles: 'Total vehicles',
    trim: 'Trim',
    type: 'Type',
    updateReorderRules: 'Update reorder rules',
    uMobNum: 'Mobile number',
    uTanazol: 'Tanazol',
    users: 'Users',
    vat: 'VAT',
    vehicleMovement: 'Vehicle movement',
    view: 'View',
    vin: 'VIN',
    warehouse: 'Warehouse',
    warehouseBreakdown: 'Warehouse breakdown',
    wheel: 'Wheel',
};

const arabicLabels: Record<string, string> = {
    actions: 'الإجراءات',
    activate: 'تفعيل',
    alerts: 'التنبيهات',
    alertsWithVin: 'تنبيهات مع رقم الهيكل',
    assignRoles: 'تعيين الأدوار',
    autoAlerts: 'التنبيهات الآلية',
    availableVehicles: 'المركبات المتاحة',
    branch: 'الفرع',
    branchPerformance: 'أداء الفرع',
    brand: 'العلامة التجارية',
    byBrand: 'حسب العلامة',
    byColor: 'حسب اللون',
    byModel: 'حسب الموديل',
    byWarehouse: 'حسب المستودع',
    cards: 'البطاقات',
    charts: 'الرسوم البيانية',
    chassis: 'رقم الهيكل',
    color: 'اللون',
    colorDistribution: 'توزيع الألوان',
    cost: 'التكلفة',
    create: 'إنشاء',
    createSnapshot: 'إنشاء لقطة',
    customerInfo: 'بيانات العميل',
    customerPhone: 'هاتف العميل',
    dashboard: 'لوحة التحكم',
    data: 'حقول البيانات',
    daysInStock: 'أيام في المخزون',
    delete: 'حذف',
    deleteSnapshot: 'حذف لقطة',
    edit: 'تعديل',
    editPermissions: 'تعديل الصلاحيات',
    editStockRules: 'تعديل قواعد المخزون',
    execute: 'تنفيذ',
    export: 'تصدير',
    fastStock: 'المخزون السريع',
    fastVehicles: 'المركبات السريعة',
    import: 'استيراد',
    inventory: 'المخزون',
    inventoryMovement: 'حركة المخزون',
    inventoryOverview: 'نظرة عامة على المخزون',
    inventoryTurnover: 'دوران المخزون',
    logistics: 'اللوجستيات',
    lowQuantityAlerts: 'تنبيهات انخفاض الكمية',
    manage: 'إدارة',
    mediumStock: 'المخزون المتوسط',
    mediumVehicles: 'المركبات المتوسطة',
    minMaxRules: 'قواعد الحد الأدنى والأقصى',
    model: 'الموديل',
    modelBreakdown: 'تفصيل الموديلات',
    modelDistribution: 'توزيع الموديلات',
    movement: 'الحركة',
    multiLocation: 'تعدد المواقع',
    overview: 'نظرة عامة',
    page: 'الصفحة',
    permissions: 'الصلاحيات',
    profit: 'الربح',
    purchaseDate: 'تاريخ الشراء',
    refreshDashboard: 'تحديث لوحة التحكم',
    reorderPointAlerts: 'تنبيهات نقطة إعادة الطلب',
    reorderReport: 'تقرير إعادة الطلب',
    reorderSuggestions: 'اقتراحات إعادة الطلب',
    replenishment: 'إعادة الطلب',
    reservedVehicles: 'المركبات المحجوزة',
    roles: 'الأدوار',
    salesByBranch: 'المبيعات حسب الفرع',
    salesByColor: 'المبيعات حسب اللون',
    salesByModel: 'المبيعات حسب الموديل',
    salesPerformance: 'أداء المبيعات',
    salesTrend: 'اتجاه المبيعات',
    salesValue: 'قيمة المبيعات',
    sellerKPIs: 'مؤشرات البائعين',
    sellerName: 'اسم البائع',
    sellerPerformance: 'أداء البائع',
    sendAlert: 'إرسال تنبيه',
    settings: 'الإعدادات',
    slowStock: 'المخزون البطيء',
    slowStockAlerts: 'تنبيهات المخزون البطيء',
    slowStockList: 'قائمة المخزون البطيء',
    slowVehicles: 'المركبات البطيئة',
    snapshots: 'اللقطات',
    snapshotHistory: 'سجل اللقطات',
    soldVehicles: 'المركبات المباعة',
    stockAgeClassification: 'تصنيف عمر المخزون',
    stockByModel: 'المخزون حسب الموديل',
    stockByModelColor: 'المخزون حسب الموديل واللون',
    stockByVin: 'المخزون حسب رقم الهيكل',
    stockByWarehouse: 'المخزون حسب المستودع',
    stockCoverage: 'تغطية المخزون',
    stockCoverageMonths: 'أشهر تغطية المخزون',
    stockHealth: 'صحة المخزون',
    stockRules: 'قواعد المخزون',
    suggestedOrders: 'الطلبات المقترحة',
    supplierInfo: 'بيانات المورد',
    sync: 'مزامنة',
    syncInventory: 'مزامنة المخزون',
    tables: 'الجداول',
    tabs: 'التبويبات',
    totalInventory: 'إجمالي المخزون',
    totalSales: 'إجمالي المبيعات',
    totalVehicles: 'إجمالي المركبات',
    trim: 'الفئة',
    updateReorderRules: 'تحديث قواعد إعادة الطلب',
    users: 'المستخدمون',
    vehicleMovement: 'حركة المركبات',
    view: 'عرض',
    vin: 'رقم الهيكل',
    warehouse: 'المستودع',
    warehouseBreakdown: 'تفصيل المستودعات',
};

Object.assign(arabicLabels, {
    absEntry: 'رقم داخلي',
    additionalRemark: 'ملاحظة إضافية',
    apInvoiceDate: 'تاريخ فاتورة الشراء',
    apInvoiceNo: 'رقم فاتورة الشراء',
    arInvoiceDate: 'تاريخ فاتورة البيع',
    arInvoiceNo: 'رقم فاتورة البيع',
    bank: 'البنك',
    bankCode: 'رمز البنك',
    baraka: 'البركة',
    chassisStatus: 'حالة الهيكل',
    companies: 'الشركات',
    contractDate: 'تاريخ العقد',
    countries: 'الدول',
    createDate: 'تاريخ الإنشاء',
    customerGroup: 'مجموعة العميل',
    customerName: 'اسم العميل',
    customerNumber: 'رقم العميل',
    dania: 'الدانية',
    displayStatus: 'حالة العرض',
    engineNo: 'رقم المحرك',
    estimatedArrival: 'الوصول المتوقع',
    exteriorColor: 'اللون الخارجي',
    grpoDate: 'تاريخ استلام الشراء',
    interiorColor: 'اللون الداخلي',
    inventoryKey: 'مفتاح المخزون',
    isInStock: 'موجود في المخزون',
    isReadyForSale: 'جاهز للبيع',
    isReserved: 'محجوز',
    isSold: 'مباع',
    itemCode: 'رمز الصنف',
    itemGroupCode: 'رمز مجموعة الصنف',
    jordan: 'الأردن',
    laith: 'الليث اللامع',
    laithCars: 'الليث',
    listName1: 'اسم قائمة الأسعار 1',
    listName2: 'اسم قائمة الأسعار 2',
    listNum1: 'رقم قائمة الأسعار 1',
    listNum2: 'رقم قائمة الأسعار 2',
    listNum3: 'رقم قائمة الأسعار 3',
    listNum4: 'رقم قائمة الأسعار 4',
    modelYear: 'سنة الموديل',
    movementCategory: 'تصنيف الحركة',
    normalizedStatus: 'الحالة الموحدة',
    notes: 'الملاحظات',
    plateNumber: 'رقم اللوحة',
    poNo: 'رقم أمر الشراء',
    price1: 'السعر 1',
    price2: 'السعر 2',
    price3: 'السعر 3',
    price4: 'السعر 4',
    quantity: 'الكمية',
    rawStatus: 'الحالة الأصلية',
    ready: 'جاهز',
    recipientName: 'اسم المستلم',
    recipientNumber: 'رقم المستلم',
    reserveDate: 'تاريخ الحجز',
    rowHash: 'بصمة السطر',
    salesMan: 'البائع',
    saudiArabia: 'السعودية',
    soldPrice: 'سعر البيع',
    soRemarks: 'ملاحظات أمر البيع',
    sourceBaseUrl: 'رابط المصدر',
    sourceCountry: 'دولة المصدر',
    sourceId: 'معرف المصدر',
    sourceName: 'اسم المصدر',
    sourceRowIndex: 'رقم السطر في المصدر',
    stockAgeDays: 'أيام عمر المخزون',
    syncRunId: 'معرف عملية المزامنة',
    type: 'النوع',
    uMobNum: 'رقم الجوال',
    uTanazol: 'التنازل',
    vat: 'ضريبة القيمة المضافة',
    wheel: 'العجلة',
});

function labelFromKey(key: string, language: 'en' | 'ar') {
    const labels = language === 'ar' ? arabicLabels : englishLabels;
    return key
        .split('.')
        .map((part) => labels[part] ?? humanize(part))
        .join(language === 'ar' ? ' / ' : ' / ');
}

function humanize(part: string) {
    return part
        .replace(/([a-z])([A-Z])/g, '$1 $2')
        .replace(/^\w/, (value) => value.toUpperCase());
}

export const permissionCatalog: PermissionCatalogItem[] = permissionKeys.map(
    (key) => ({
        key,
        labelEn: labelFromKey(key, 'en'),
        labelAr: labelFromKey(key, 'ar'),
        description: `Allows ${labelFromKey(key, 'en').toLowerCase()}.`,
        category: categoryFromKey(key),
    }),
);

function categoryFromKey(key: string) {
    if (key.includes('.page.')) {
        return 'pages';
    }
    if (key.includes('.cards.')) {
        return 'dashboard-cards';
    }
    if (key.includes('.tabs.')) {
        return 'tabs';
    }
    if (key.includes('.tables.')) {
        return 'tables-reports';
    }
    if (key.includes('.charts.')) {
        return 'charts';
    }
    if (key.startsWith('data.')) {
        return 'data-fields';
    }
    if (key.startsWith('countries.')) {
        return 'countries';
    }
    if (key.startsWith('companies.')) {
        return 'companies';
    }
    if (key.startsWith('actions.')) {
        return 'actions';
    }
    if (key.startsWith('users.')) {
        return 'users';
    }
    if (key.startsWith('roles.')) {
        return 'roles';
    }
    if (key.startsWith('permissions.')) {
        return 'permissions';
    }
    if (key.startsWith('settings.')) {
        return 'settings';
    }
    if (key.startsWith('inventory.')) {
        return 'inventory';
    }
    if (key.startsWith('alerts.')) {
        return 'alerts';
    }
    if (key.startsWith('replenishment.')) {
        return 'replenishment';
    }
    if (key.startsWith('salesPerformance.')) {
        return 'sales-performance';
    }
    if (key.startsWith('stockCoverage.')) {
        return 'stock-coverage';
    }
    if (key.startsWith('stockRules.')) {
        return 'stock-rules';
    }
    if (key.startsWith('snapshots.')) {
        return 'snapshots';
    }
    if (key.startsWith('logistics.')) {
        return 'logistics';
    }
    if (key.startsWith('multiLocation.')) {
        return 'multi-location';
    }
    return 'general';
}
