import type {
  DashboardMetric,
  InventoryAlert,
  InventoryItem,
  LocationStock,
  LogisticsStatus,
  SalesPerformanceItem,
} from "@/types/inventory";

export const inventoryItems: InventoryItem[] = [
  {
    absEntry: 10021,
    chassis: "JTDBR32E720145982",
    itemCode: "TY-COR-2026-WHT",
    model: "Corolla Hybrid",
    itemGroupCode: 101,
    type: "Sedan",
    modelYear: "2026",
    exteriorColor: "Pearl White",
    interiorColor: "Black",
    wheel: "17 Alloy",
    notes: "Ready for showroom display",
    quantity: 18,
    branch: "Amman Main",
    ready: true,
    brand: "Toyota",
    engineNo: "2ZR-8H9231",
    poNo: "PO-2026-041",
    estimatedArrival: "2026-05-18",
    grpoDate: "2026-04-25",
    salesMan: "Leen Haddad",
    arInvoiceDate: "2026-05-03",
    soldPrice: 24600,
    vat: 3936,
    customerName: "Retail Walk-in",
    customerGroup: "Retail",
    plateNumber: "29-44112",
    apInvoiceDate: "2026-04-21",
    apInvoiceNo: "AP-77891",
    chassisStatus: "available",
    arInvoiceNo: "AR-50122",
    cardCode: "C1009",
    createDate: "2026-04-12",
    warehouse: "Main WH",
    reserveDate: "",
    movementVelocity: "fast",
    coverageMonths: 1.8,
  },
  {
    absEntry: 10044,
    chassis: "WBA5R1C01LFH82211",
    itemCode: "BMW-X5-2025-BLK",
    model: "X5 xDrive40i",
    itemGroupCode: 204,
    type: "SUV",
    modelYear: "2025",
    exteriorColor: "Carbon Black",
    interiorColor: "Mocha",
    wheel: "20 Sport",
    notes: "Reserved pending bank approval",
    quantity: 7,
    branch: "Sweifieh",
    ready: true,
    brand: "BMW",
    engineNo: "B58-22601",
    poNo: "PO-2026-029",
    estimatedArrival: "2026-05-25",
    grpoDate: "2026-03-14",
    salesMan: "Omar Qasem",
    arInvoiceDate: "",
    soldPrice: 68400,
    vat: 10944,
    customerName: "Al Noor Leasing",
    customerGroup: "Fleet",
    plateNumber: "",
    apInvoiceDate: "2026-03-11",
    apInvoiceNo: "AP-77210",
    chassisStatus: "reserved",
    arInvoiceNo: "",
    cardCode: "C2041",
    createDate: "2026-03-10",
    warehouse: "Premium WH",
    reserveDate: "2026-05-02",
    movementVelocity: "medium",
    coverageMonths: 3.4,
  },
  {
    absEntry: 10067,
    chassis: "KM8K12AA5NU901236",
    itemCode: "HY-KON-2024-RED",
    model: "Kona",
    itemGroupCode: 118,
    type: "Crossover",
    modelYear: "2024",
    exteriorColor: "Pulse Red",
    interiorColor: "Gray",
    wheel: "16 Alloy",
    notes: "Ageing stock review required",
    quantity: 24,
    branch: "Irbid",
    ready: false,
    brand: "Hyundai",
    engineNo: "G4FL-99012",
    poNo: "PO-2025-188",
    estimatedArrival: "2026-05-10",
    grpoDate: "2025-12-08",
    salesMan: "Maya Nasser",
    arInvoiceDate: "",
    soldPrice: 21400,
    vat: 3424,
    customerName: "",
    customerGroup: "",
    plateNumber: "",
    apInvoiceDate: "2025-12-03",
    apInvoiceNo: "AP-74118",
    chassisStatus: "service-hold",
    arInvoiceNo: "",
    cardCode: "",
    createDate: "2025-12-01",
    warehouse: "North WH",
    reserveDate: "",
    movementVelocity: "slow",
    coverageMonths: 7.2,
  },
  {
    absEntry: 10092,
    chassis: "SALWA2BU8PA113901",
    itemCode: "LR-RRS-2026-GRY",
    model: "Range Rover Sport",
    itemGroupCode: 304,
    type: "Luxury SUV",
    modelYear: "2026",
    exteriorColor: "Eiger Grey",
    interiorColor: "Ebony",
    wheel: "21 Diamond",
    notes: "At port clearance",
    quantity: 5,
    branch: "Amman Main",
    ready: false,
    brand: "Land Rover",
    engineNo: "P400-44190",
    poNo: "PO-2026-055",
    estimatedArrival: "2026-05-20",
    grpoDate: "",
    salesMan: "Kareem Saleh",
    arInvoiceDate: "",
    soldPrice: 98200,
    vat: 15712,
    customerName: "",
    customerGroup: "",
    plateNumber: "",
    apInvoiceDate: "",
    apInvoiceNo: "",
    chassisStatus: "in-transit",
    arInvoiceNo: "",
    cardCode: "",
    createDate: "2026-04-28",
    warehouse: "Port",
    reserveDate: "",
    movementVelocity: "medium",
    coverageMonths: 2.9,
  },
];

export const dashboardMetrics: DashboardMetric[] = [
  { label: "Total Stock Units", value: "1,284", trend: "+4.8% vs Apr", tone: "positive" },
  { label: "Fast Moving Stock", value: "462", trend: "36% of fleet", tone: "positive" },
  { label: "Medium Moving Stock", value: "517", trend: "Stable mix", tone: "neutral" },
  { label: "Slow Moving Stock", value: "305", trend: "Needs review", tone: "warning" },
  { label: "Stock Coverage Months", value: "3.7", trend: "-0.4 months", tone: "positive" },
  { label: "Sold Units This Month", value: "188", trend: "+12 units", tone: "positive" },
  { label: "Reserved Units", value: "96", trend: "42 pending approval", tone: "neutral" },
  { label: "In Transit Units", value: "143", trend: "27 due this week", tone: "warning" },
];

export const alerts: InventoryAlert[] = [
  {
    id: "ALT-1001",
    title: "Slow stock threshold exceeded",
    message: "Kona 2024 in Irbid has crossed the ageing threshold.",
    severity: "warning",
    branch: "Irbid",
    createdAt: "2026-05-06 09:10",
  },
  {
    id: "ALT-1002",
    title: "Low coverage on Corolla Hybrid",
    message: "Fast moving sedan coverage is below two months.",
    severity: "critical",
    branch: "Amman Main",
    createdAt: "2026-05-06 08:45",
  },
  {
    id: "ALT-1003",
    title: "Port arrival updated",
    message: "Range Rover Sport shipment ETA moved to May 20.",
    severity: "info",
    branch: "Amman Main",
    createdAt: "2026-05-05 16:30",
  },
];

export const locationStocks: LocationStock[] = [
  { location: "Amman Main", available: 412, reserved: 38, inTransit: 61, slowMoving: 84 },
  { location: "Sweifieh", available: 238, reserved: 27, inTransit: 34, slowMoving: 56 },
  { location: "Irbid", available: 174, reserved: 16, inTransit: 22, slowMoving: 73 },
  { location: "Aqaba Port", available: 31, reserved: 0, inTransit: 26, slowMoving: 8 },
];

export const salesPerformance: SalesPerformanceItem[] = [
  { model: "Corolla Hybrid", brand: "Toyota", unitsSold: 52, revenue: 1279200, margin: "14.6%" },
  { model: "X5 xDrive40i", brand: "BMW", unitsSold: 13, revenue: 889200, margin: "11.2%" },
  { model: "Kona", brand: "Hyundai", unitsSold: 24, revenue: 513600, margin: "9.8%" },
  { model: "Range Rover Sport", brand: "Land Rover", unitsSold: 6, revenue: 589200, margin: "12.1%" },
];

export const logisticsStatuses: LogisticsStatus[] = [
  { shipment: "Ocean Freight 224A", poNo: "PO-2026-055", status: "Port clearance", eta: "2026-05-20", units: 18, branch: "Amman Main" },
  { shipment: "Carrier Batch 18", poNo: "PO-2026-041", status: "Inland transfer", eta: "2026-05-18", units: 42, branch: "Amman Main" },
  { shipment: "Regional Shuttle 07", poNo: "PO-2026-062", status: "Scheduled", eta: "2026-05-22", units: 12, branch: "Irbid" },
];
